name: Build and Deploy Agent to ACI

on:
  push:
    branches:
      - main # Adjust this as necessary for your workflow triggers

env:
  IMAGE_NAME: container-agent # Replace with your image name
  REGISTRY_NAME: acrpipelinepractice # Replace with your ACR name
  RESOURCE_GROUP: pipeline-practice # Replace with your resource group name
  ACI_NAME: agent-container-instance # Replace with your ACI name
  LOCATION: uksouth # Replace with your Azure region, e.g., "eastus"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image to ACR
        run: |
          az acr build --registry $REGISTRY_NAME --image $IMAGE_NAME .

      - name: Deploy to ACI
        run: |
          az container create \
            --resource-group $RESOURCE_GROUP \
            --name $ACI_NAME \
            --image $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:latest \
            --cpu 1 --memory 1.5 \
            --environment-variables \
              AZP_URL=$AZP_URL \
              AZP_TOKEN=$AZP_TOKEN \
              AZP_AGENT_NAME=$AZP_AGENT_NAME \
              AZP_POOL=$AZP_POOL \
            --location $LOCATION
        env:
          AZP_URL: ${{ secrets.AZP_URL }}
          AZP_TOKEN: ${{ secrets.AZP_TOKEN }}
          AZP_AGENT_NAME: ${{ secrets.AZP_AGENT_NAME }}
          AZP_POOL: ${{ secrets.AZP_POOL }}