name: Build and Deploy Agent to ACI

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch

env:
  IMAGE_NAME: container-agent # Replace with your image name
  REGISTRY_NAME: acrpipelinepractice # Replace with your ACR name
  RESOURCE_GROUP: pipeline-practice # Replace with your resource group name
  ACI_NAME: agent-container-instance # Replace with your ACI name
  LOCATION: uksouth # Replace with your Azure region, e.g., "eastus"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build the Docker image
        run: |
          docker build . -t ${{ env.IMAGE_NAME }}:latest

      - name: Log in to ACR
        run: |
          az acr login --name ${{ env.REGISTRY_NAME }}

      - name: Tag the Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Push the Docker image to ACR
        run: |
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to ACI
        run: |
          az container create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.ACI_NAME }} \
            --image ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest \
            --cpu 1 --memory 1.5 \
            --environment-variables \
              AZP_URL=${{ secrets.AZP_URL }} \
              AZP_TOKEN=${{ secrets.AZP_TOKEN }} \
              AZP_AGENT_NAME=${{ secrets.AZP_AGENT_NAME }} \
              AZP_POOL=${{ secrets.AZP_POOL }} \
            --location ${{ env.LOCATION }}
