name: Build, Tag and Push Agent to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version tag
        id: version
        run: echo "VERSION_TAG=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build . -t acrpipelinepractice.azurecr.io/agent:${{ env.VERSION_TAG }}

      - name: Push Docker image to ACR
        run: |
          az acr login --name acrpipelinepractice
          docker push acrpipelinepractice.azurecr.io/agent:${{ env.VERSION_TAG }}

      - name: Create and push git tag
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Action"
          git tag ${{ env.VERSION_TAG }}
          git push origin ${{ env.VERSION_TAG }}

      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: pipeline-practice 
          dns-name-label: pipeline-practice-agent
          image: acrpipelinepractice.azurecr.io/agent:${{ env.VERSION_TAG }}
          registry-login-server: acrpipelinepractice.azurecr.io
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: pipeline-practice-agent
          location: uksouth
          environment-variables: |
            AZDO_URL=${{ secrets.AZDO_URL }}
            AZDO_PAT=${{ secrets.AZDO_PAT }}
            AZDO_POOL=${{ secrets.AZDO_POOL }}

